// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError = { "code": "Docker", "message": string } | { "code": "DockerOps", "message": string } | { "code": "Database", "message": string } | { "code": "DockerNotConnected" } | { "code": "NotFound", "message": string } | { "code": "Generic", "message": string };
