// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageInfo = { id: string, repo_tags: Array<string>, size: bigint, created: bigint, };
