// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkContainer } from "./NetworkContainer";

export type NetworkInfo = { id: string, name: string, driver: string, scope: string, subnet: string, gateway: string, containers: Array<NetworkContainer>, };
