// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PullProgress = { id: string | null, status: string | null, progress: string | null, current: bigint | null, total: bigint | null, };
