// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerStats = { cpu_percent: number, mem_used_mb: number, mem_limit_mb: number, };
