// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerInfo = { id: string, name: string, image: string, status: string, state: string, ports: Array<string>, created: number, compose_project: string | null, };
