// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostStats = { cpu_percent: number, mem_used_mb: number, mem_total_mb: number, disk_used_gb: number, disk_total_gb: number, };
